runtime: php
env: flex

beta_settings:
    cloud_sql_instances: 'cloud-next-php:us-central1:cloud-next-php'

runtime_config:
    document_root: .

env_variables:
    WORDPRESS_DB_HOST: YOUR_HOST
    WORDPRESS_DB_USER: YOUR_USER
    WORDPRESS_DB_PASSWORD: YOUR_PASSWORD
