# This file configures the faceswap application frontend. The frontend serves
# public web traffic.
apiVersion: v1
kind: Service
metadata:
  name: faceswap-wordpress
  labels:
    app: faceswap
    tier: wordpress
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: faceswap
    tier: wordpress
---
apiVersion: apps/v1beta1
# apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: faceswap-wordpress
  labels:
    app: faceswap
# The faceswap wordpress replica set ensures that at least 3
# instances of the faceswap app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faceswap
        tier: wordpress
    spec:
      containers:
      # Configuration for the Wordpress frontend container
      - name: faceswap-wordpress
        # Replace $GCLOUD_PROJECT with your project ID or use `make template`.
        image: gcr.io/cloud-next-php/faceswap-wordpress
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        # The faceswap process listens on port 8080 for web traffic by default.
        env:
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - name: http-server
          containerPort: 8080
